# Generated by Django 2.1 on 2019-07-30 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190730_1152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='genItemsList',
        ),
    ]
